thrift: fixup trace_id serialization
fixes errors like:
```
 File "/usr/lib/python2.7/dist-packages/thriftpy2/thrift.py", line 153, in write
    oprot.write_struct(self)
  File "cybin.pyx", line 477, in cybin.TCyBinaryProtocol.write_struct (thriftpy2/protocol/cybin/cybin.c:6630)
  File "cybin.pyx", line 474, in cybin.TCyBinaryProtocol.write_struct (thriftpy2/protocol/cybin/cybin.c:6561)
  File "cybin.pyx", line 214, in cybin.write_struct (thriftpy2/protocol/cybin/cybin.c:3198)
thriftpy2.thrift.TDecodeException: Field 'trace_id(1)' of 'Span' needs type 'I64', but the value is `12759148914174905215L`
```

zipkin expects trace id to be formated binary-like in bigendian.

Signed-off-by: Arthur Gautier <baloo@gandi.net>